{
 "title": "Humedad y Temperatura",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  (temperatura + temperatura_ds18b20)/2 as Promedio\nFROM botdata\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  humedad AS Humedad\nFROM botdata\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Humedad y Temperatura",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time,$__interval),\n  humedad AS \"Humedad\",\n  temperatura AS \"Temperatura_BME280\",\n  temperatura_DS18B20 AS \"Temperatura_DS18B20\"\nFROM botdata\nWHERE\n  $__timeFilter(date_time)\nGROUP BY 1\nORDER BY $__timeGroup(date_time,$__interval)"
    }
   ]
  }
 ]
}